routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Frontend\FrontendPostController@index')->name('welcome');
Route::get('buy/book/{id}','BuybookController@index')->name('buy.book');
Route::post('book/order','BuybookController@stor')->name('addOrder');


Route::get('book/details/{id}','Frontend\FrontendPostController@bookdetails')->name('book.details');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
    Route::get('settings','UserController@index')->name('settings');
    Route::put('update-password','UserController@updatepassword')->name('pasword.update');
    Route::put('userNameEmail','UserController@userNameEmail')->name('useremail.update');
    route::get('showAllBook','PostController@index')->name('index');
    Route::get('addPost','PostController@postCreate')->name('post.create');
    Route::post('postStor','PostController@postStor')->name('post.stor');
    Route::get('ShowPOst/{id}','PostController@showPost')->name('post.show');
    Route::get('postEdit/{id}','PostController@editPost')->name('post.edit');
    Route::put('post/update/{id}','PostController@updatePost')->name('post.update');
    Route::delete('post/delete/{id}','PostController@destroy')->name('destroy');


    Route::get('all/order','OrderController@index')->name('all.order');
    Route::get('order/view/{id}','OrderController@orderview')->name('order.view');
    Route::delete('order/delete/{id}','OrderController@destroyOrder')->name('order.destroy');
    Route::get('pending/order','OrderController@pendingOrder')->name('pending.order');
    Route::get('order/approve/{id}','OrderController@approveOrder')->name('order.approve');
});

resources/views/admin/allorder.blade.php
@extends('layouts.admin.app')

@push('css')
@endpush

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="container-fluid">
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                    ALL Order
                                    <span class="badge bg-blue">{{ $orders->count() }}</span>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Thana</th>
                                            <th>Jela</th>
                                            <th>Post Office</th>
                                            <th>Post Code</th>
                                            <th>Mobile Nu-1</th>
                                            <th>Mobile Nu-</th>
                                            <th>Bkash M-N</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Thana</th>
                                            <th>Jela</th>
                                            <th>Post Office</th>
                                            <th>Post Code</th>
                                            <th>Mobile Nu-1</th>
                                            <th>Mobile Nu-2</th>
                                            <th>Bkash s-N</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($orders as $key=>$order)
                                            <tr>
                                                <td>{{ $key + 1}}</td>
                                                <td>{{$order->name}}</td>
                                                <td>{{$order->thana}}</td>
                                                <td>{{$order->jela}}</td>
                                                <td>{{$order->postOffic}}</td>
                                                <td>{{$order->postCod}}</td>
                                                <td>{{$order->mobileNumber1}}</td>
                                                <td>{{$order->mobileNumber2}}</td>
                                                <td>{{$order->bkashNumber}}</td>

                                                
                                                <td>
                                                    <img src="{{asset('storage/app/public/post/'.$order->post->image)}}" height="130px" width="100px" alt="book">
                                                </td>
                                                <td class="text-center">
                                                    <a href="{{route('admin.order.view',$order->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">visibility</i>
                                                    </a>
                                                    
                                                    <form id="delete-form-" action="{{route('admin.order.destroy',$order->id)}}" method="POST" >
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger waves-effect" type="submit">
                                                             <i class="material-icons">delete</i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                    {{ $orders->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>

        </div>
     </div>
</section>

@endsection


@push('js')
@endpush

resources/views/admin/createPost.blade.php
@extends('layouts.admin.app')
@section('title','post Create')

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
        <div class="container-fluid">
            <!-- Vertical Layout | With Floating Label -->
         <form action="{{route('admin.post.stor')}}" method="POST" enctype="multipart/form-data">
              @csrf
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Add New Post
                            </h2>
                        </div>
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" id="AuthorName" name="authorName" class="form-control" required>
                                        <label class="form-label">Author Name</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" id="title" name="title" class="form-control" required>
                                        <label class="form-label">Post Title</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="number" id="price" name="price" class="form-control" required>
                                        <label class="form-label">Price</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <label for="image">Feature Image</label>
                                    input
                                    <input type="file" name="image" accept="image/*">
                                </div>
                                <div class="form-group">
                                    <input type="checkbox" id="publish" class="filled-in" name="status" value="1">
                                    <label for="publish">Publish</label>
                                </div>

                        </div>
                    </div>
                </div>
            </div>


             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Description
                            </h2>
                        </div>
                        <div class="body">
                            <textarea id="tinymce" name="body"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                About Author
                            </h2>
                        </div>
                        <div class="body">
                            <textarea id="tinymce" name="aboutAuthor"></textarea>
                        </div>
                        <br>
                                
                    </div>
                </div>
            </div>
            <a href="{{route('admin.index')}}" class="btn btn-danger m-t-15 waves-effect">Back</a>
            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Submit</button>
         </form> 
        </div>

        </div>
     </div>
</section>
@endsection

@push('js')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script>tinymce.init({selector:'textarea'});</script>
@endpush

resources/views/admin/edit.blade.php
@extends('layouts.admin.app')
@section('title','post Create')

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
        <div class="container-fluid">
            <!-- Vertical Layout | With Floating Label -->
         <form action="{{route('admin.post.update',$post->id)}}" method="POST" enctype="multipart/form-data">
              @csrf
              @method('PUT')
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Add New Post
                            </h2>
                        </div>
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" id="AuthorName" name="authorName" class="form-control" value="{{$post->authorName}}" required>
                                        <label class="form-label">Author Name</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" id="title" name="title" class="form-control" value="{{$post->title}}" required>
                                        <label class="form-label">Post Title</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="number" id="price" name="price" class="form-control" value="{{$post->price}}" required>
                                        <label class="form-label">Price</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <label for="image">Feature Image</label>
                                    input
                                    <input type="file" name="image" accept="image/*">
                                </div>
                                <div class="form-group">
                                    <input type="checkbox" id="publish" class="filled-in" name="status" value="1" {{$post->status == true ? 'checked' : ''}}>
                                    <label for="publish">Publish</label>
                                </div>

                        </div>
                    </div>
                </div>
            </div>


             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Description
                            </h2>
                        </div>
                        <div class="body">
                            <textarea id="tinymce" name="body">{!!$post->body!!}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                About Author
                            </h2>
                        </div>
                        <div class="body">
                            <textarea id="tinymce" name="aboutAuthor">{!!$post->aboutAuthor!!}</textarea>
                        </div>
                        <br>
                                
                    </div>
                </div>
            </div>
            <a href="{{route('admin.index')}}" class="btn btn-danger m-t-15 waves-effect">Back</a>
            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
         </form> 
        </div>

        </div>
     </div>
</section>
@endsection

@push('js')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script>tinymce.init({selector:'textarea'});</script>
@endpush

resources/views/admin/index.blade.php
@extends('layouts.admin.app')

@push('css')
@endpush

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="container-fluid">
            <div class="block-header">
                <a class="btn btn-primary waves-effect" href="{{route('admin.post.create')}}">
                	<i class="material-icons">add</i>
                	<span>Add New Post</span>
            	</a>
            </div>
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                    ALL Post
                                    <span class="badge bg-blue">{{ $posts->count() }}</span>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Author Name</th>
                                            <th>Title</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                            <th>Image</th>
                                            <th>Updated At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <tr>
                                            <th>ID</th>
                                            <th>Author Name</th>
                                            <th>Title</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                            <th>Image</th>
                                            <th>Updated At</th>
                                            <th>Action</th>
                                        </tr>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($posts as $key=>$post)
                                            <tr>
                                                <td>{{ $key + 1}}</td>
                                                <td>{{$post->authorName}}</td>
                                                <td>{{ Illuminate\Support\Str::limit($post->title, 30, $end='....')}}</td>
                                                <td>{{$post->price}}</td>
                                                <td>
                                                    @if($post->status == true)
                                                     <span class="badge bg-blue">Approved</span>
                                                     @else
                                                     <span class="badge bg-pink">Pending</span>
                                                    @endif
                                                </td>
                                                <td>
                                                    <img src="{{asset('storage/app/public/post/'.$post->image)}}" height="130px" width="100px" alt="book">
                                                </td>
                                                <td>{{ $post->updated_at}}</td>
                                                <td class="text-center">
                                                    <a href="{{route('admin.post.show',$post->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">visibility</i>
                                                    </a>
                                                    <a href="{{route('admin.post.edit',$post->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    
                                                    <form id="delete-form-" action="{{route('admin.destroy',$post->id)}}" method="POST" >
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger waves-effect" type="submit">
                                                             <i class="material-icons">delete</i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                {{$posts->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>

        </div>
     </div>
</section>

@endsection


@push('js')
@endpush

resources/views/admin/orderPending.blade.php
@extends('layouts.admin.app')

@section('title','panding order')

@push('css')
@endpush

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="container-fluid">
            <div class="block-header">
                
            </div>
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                    ALL pending order
                                    <span class="badge bg-blue">{{ $pendings->count() }}</span>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Thana</th>
                                            <th>Jela</th>
                                            <th>Post Office</th>
                                            <th>Post Code</th>
                                            <th>Mobile Nu-1</th>
                                            <th>Mobile Nu-</th>
                                            <th>Bkash M-N</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Thana</th>
                                            <th>Jela</th>
                                            <th>Post Office</th>
                                            <th>Post Code</th>
                                            <th>Mobile Nu-1</th>
                                            <th>Mobile Nu-</th>
                                            <th>Bkash M-N</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($pendings as $key=>$pending)
                                            <tr>
                                                <td>{{ $key + 1}}</td>
                                                <td>{{$pending->name}}</td>
                                                <td>{{$pending->thana}}</td>
                                                <td>{{$pending->jela}}</td>
                                                <td>{{$pending->postOffic}}</td>
                                                <td>{{$pending->postCod}}</td>
                                                <td>{{$pending->mobileNumber1}}</td>
                                                <td>{{$pending->mobileNumber2}}</td>
                                                <td>{{$pending->bkashNumber}}</td>

                                                
                                                <td>
                                                    <img src="{{asset('storage/app/public/post/'.$pending->post->image)}}" height="130px" width="100px" alt="book">
                                                </td>
                                                <td class="text-center">
                                                    <a href="{{route('admin.order.view',$pending->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">visibility</i>
                                                    </a>
                                                    <a href="{{route('admin.order.approve',$pending->id)}}" class="btn btn-info waves-effect">
                                                        approve
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>

        </div>
     </div>
</section>

@endsection


@push('js')
@endpush

resources/views/admin/show.blade.php
@extends('layouts.admin.app')
@section('title','post show')

@section('contain')
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
        <div class="container-fluid">
            <!-- Vertical Layout | With Floating Label -->
         
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Show Post
                            </h2>
                        </div>
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                       <strong>Author Name:</strong> <p>{{$post->authorName}}</p>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <strong>Title:</strong>
                                        <p>{{$post->title}}</p>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <strong>Price:</strong>
                                        <p>{{$post->price}}</p>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <img src="{{asset('storage/app/public/post/'.$post->image)}}" class="img-fluid" alt="book Image">
                                </div>
                                <div class="form-group">
                                    <strong>Publication Status:</strong>
                                    <p>{{$post->status == true ? 'published' : 'Unpublish'}}</p>
                                </div>

                        </div>
                    </div>
                </div>
            </div>


             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Description
                            </h2>
                        </div>
                        <div class="body">
                            {!!$post->body!!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                About Author
                            </h2>
                        </div>
                        <div class="body">
                            {!!$post->aboutAuthor!!}
                        </div>
                        <br>
                                
                    </div>
                </div>
            </div>
            <a href="{{route('admin.index')}}" class="btn btn-danger m-t-15 waves-effect">Back</a>
           
        </div>

        </div>
     </div>
</section>
@endsection

@push('js')
@endpush